services:
  web-app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./service:/service
    environment:
      - DB_HOST=db
      - DB_NAME=dbname
      - DB_USER=user
      - DB_PASS=pass
    command: >
      sh -c "python manage.py migrate &&
             echo \"from django.contrib.auth import get_user_model; User = get_user_model(); User.objects.create_superuser('root', 'root@root.com', 'root') if not User.objects.filter(username='root').exists() else None\" | python manage.py shell &&
             python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db

  db:
    image: postgres:14.6-alpine
    environment:
      - POSTGRES_DB=dbname
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass

  redis:
    image: redis:7.0-alpine
    hostname: redis

  worker:
    build:
      context: .
    hostname: worker
    entrypoint: ["celery"]
    command: ["-A", "celery_app.app", "worker", "--loglevel=info"]
    volumes:
      - ./service:/service
    depends_on:
      - redis



  flower:
    build:
      context: .
    hostname: flower
    entrypoint: celery
    command: -A celery_app.app flower
    volumes:
      - ./service:/service
    links:
      - redis
    depends_on:
      - redis
    ports:
      - "5555:5555"


