# Generated by Django 3.2.16 on 2024-04-11 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='plan_type',
            field=models.CharField(choices=[('full', 'FULL'), ('student', 'STUDENT'), ('discount', 'DISCOUNT')], default='full', max_length=10),
        ),
    ]
